import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} `}
      >

<ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          
         
       <main className="relative min-h-screen container mx-auto pt-40">{children}
          <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
            {/* Blue glow */}
            <div className="absolute top-0 left-0 w-96 h-96 bg-blue-500 rounded-full blur-[120px] opacity-40"></div>
            {/* Green glow */}
            <div className="absolute bottom-0 right-0 w-96 h-96 bg-green-500 rounded-full blur-[120px] opacity-40"></div>
          </div>
        </main> 
        </ThemeProvider>
      </body>
    </html>
  );
}
